### ISSUE TITLE
WEBGL UniTask.SwitchToThreadPool() 

### ISSUE THREAD

**Issue by michaellu88** [mochi-neko/StbImageSharpForUnity#2]
is there any workaround for this code to run on webgl since UniTask.SwitchToThreadPool() does not support webgl.
i have try switch to unitask.create() but it still block the main thread on webgl when i try to load univrm texture on runtime. tq

**Comment by mochi-neko** [comment]
I'm sorry I don't know much about the UniTask on WebGL.
WebGL does not support multi-threading, but you may use this experimental feature:

https://docs.unity3d.com/ScriptReference/PlayerSettings.WebGL-threadsSupport.html
